from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('league/', views.league, name='leaguepage'),
    path('motogp/', views.motogp, name='motogppage'),
    path('formula1/', views.formula1, name='formula1page'),
    path('expense_tracking/', views.ExpenseTrackingView.as_view(), name='expensetrackingpage'),
    path('expense_tracking/nepal-savings/add/', views.nepal_savings_add, name='nepal_savings_add'),
    path('expense_tracking/nepal-savings/use/', views.nepal_savings_use, name='nepal_savings_use'),
    path('expense_tracking/nepal-savings/<int:pk>/update/', views.nepal_savings_update, name='nepal_savings_update'),
    path('expense_tracking/nepal-savings/<int:pk>/delete/', views.nepal_savings_delete, name='nepal_savings_delete'),
    path('expense_tracking/money-to-get/add/', views.money_to_get_add, name='money_to_get_add'),
    path('expense_tracking/money-to-get/<int:pk>/update/', views.money_to_get_update, name='money_to_get_update'),
    path('expense_tracking/money-to-get/<int:pk>/delete/', views.money_to_get_delete, name='money_to_get_delete'),
    path('expense_tracking/money-to-pay/add/', views.money_to_pay_add, name='money_to_pay_add'),
    path('expense_tracking/money-to-pay/<int:pk>/update/', views.money_to_pay_update, name='money_to_pay_update'),
    path('expense_tracking/money-to-pay/<int:pk>/delete/', views.money_to_pay_delete, name='money_to_pay_delete'),
    path('expense_tracking/convert-currency/', views.convert_currency, name='convert_currency'),
    path('stockex_dash/', views.stockex, name='stockexpage'),
    path('stockex_dash/live-data/', views.nepse_live_data, name='nepse_live_data'),
    path('stockex_dash/portfolio/symbols/', views.portfolio_symbols, name='portfolio_symbols'),
    path('stockex_dash/portfolio/add/', views.portfolio_add, name='portfolio_add'),
    path('stockex_dash/portfolio/<int:pk>/update/', views.portfolio_update, name='portfolio_update'),
    path('stockex_dash/portfolio/<int:pk>/delete/', views.portfolio_delete, name='portfolio_delete'),
    path('stockex_dash/alerts/check/', views.price_alerts_check, name='price_alerts_check'),
    path('stockex_dash/alerts/add/', views.price_alert_add, name='price_alert_add'),
    path('stockex_dash/alerts/<int:pk>/update/', views.price_alert_update, name='price_alert_update'),
    path('stockex_dash/alerts/<int:pk>/delete/', views.price_alert_delete, name='price_alert_delete'),
]