# Generated by Django 6.0.7 on 2026-09-03 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodis_app', '0002_seed_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buy_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
