# Generated by Django 6.0.7 on 2026-09-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodis_app', '0003_portfolioholding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_direction', models.CharField(blank=True, choices=[('up', 'Crossed above'), ('down', 'Dropped below')], max_length=4)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_triggered', '-created_at'],
            },
        ),
    ]
