# Generated by Django 6.0.7 on 2026-09-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodis_app', '0004_pricealert'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='action',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4),
        ),
    ]
