# Generated by Django 6.0.7 on 2026-10-01 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodis_app', '0007_alertrecipient_pricealert_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyportfolioholding',
            name='buy_date',
        ),
        migrations.RemoveField(
            model_name='familyportfolioholding',
            name='buy_price',
        ),
    ]
