# Generated by Django 6.0.7 on 2026-10-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodis_app', '0008_remove_familyportfolioholding_buy_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='message_sent',
            field=models.BooleanField(default=False, help_text='Whether the WhatsApp alert message was actually delivered.'),
        ),
    ]
