# Generated by Django 6.0.7 on 2026-10-01 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodis_app', '0009_pricealert_message_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='holder',
            field=models.ForeignKey(blank=True, help_text="Which family member's share this alert is about (purely informational - doesn't change who gets notified).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_alerts', to='nodis_app.familymember'),
        ),
    ]
